### ISSUE TITLE
Error: invalid conversion from 'int*' to 'int32_t*' {aka 'long int*'} [-fpermissive]

### ISSUE THREAD

**Issue by NINI1988** [google/googletest#2918]
When I compile the current version of Googletest I get the following error.
The previous Googletest version 1.8.1 has worked before.
Googletest is complied for the platform arm32v7.

````
In file included from ../../../Tools/googletest/googlemock/src/gmock-all.cc:46:
 ../../../Tools/googletest/googlemock/src/gmock.cc: In function 'bool testing::internal::ParseGoogleMockIntFlag(const char*, const char*, int*)':
 ../../../Tools/googletest/googlemock/src/gmock.cc:136:32: error: invalid conversion from 'int*' to 'int32_t*' {aka 'long int*'} [-fpermissive]
   136 |                     value_str, value);
       |                                ^~~~~
       |                                |
       |                                int*
 In file included from ../../../Tools/googletest/googlemock/include/gmock/internal/gmock-port.h:56,
                  from ../../../Tools/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:46,
                  from ../../../Tools/googletest/googlemock/include/gmock/gmock-actions.h:145,
                  from ../../../Tools/googletest/googlemock/include/gmock/gmock.h:59,
                  from ../../../Tools/googletest/googlemock/src/gmock-all.cc:39:
 ../../../Tools/googletest/googletest/include/gtest/internal/gtest-port.h:2224:37: note:   initializing argument 3 of 'bool testing::internal::ParseInt32(const testing::Message&, const char*, int32_t*)'
  2224 |                            int32_t* value);
       |                            ~~~~~~~~~^~~~~
 In file included from ../../../Tools/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:46,
                  from ../../../Tools/googletest/googlemock/include/gmock/gmock-actions.h:145,
                  from ../../../Tools/googletest/googlemock/include/gmock/gmock.h:59,
                  from ../../../Tools/googletest/googlemock/src/gmock-all.cc:39:
 ../../../Tools/googletest/googlemock/src/gmock.cc: In instantiation of 'void testing::internal::InitGoogleMockImpl(int*, CharType**) [with CharType = char]':
 ../../../Tools/googletest/googlemock/src/gmock.cc:192:42:   required from here
 ../../../Tools/googletest/googlemock/include/gmock/internal/gmock-port.h:67:26: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
    67 | #define GMOCK_FLAG(name) FLAGS_gmock_##name
       |                          ^~~~~~~~~~~~
       |                          |
       |                          int32_t* {aka long int*}
 ../../../Tools/googletest/googlemock/src/gmock.cc:159:33: note: in expansion of macro 'GMOCK_FLAG'
   159 |                                &GMOCK_FLAG(default_mock_behavior))) {
       |                                 ^~~~~~~~~~
 In file included from ../../../Tools/googletest/googlemock/src/gmock-all.cc:46:
 ../../../Tools/googletest/googlemock/src/gmock.cc:127:41: note:   initializing argument 3 of 'bool testing::internal::ParseGoogleMockIntFlag(const char*, const char*, int*)'
   127 |                                    int* value) {
       |                                    ~~~~~^~~~~
 In file included from ../../../Tools/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:46,
                  from ../../../Tools/googletest/googlemock/include/gmock/gmock-actions.h:145,
                  from ../../../Tools/googletest/googlemock/include/gmock/gmock.h:59,
                  from ../../../Tools/googletest/googlemock/src/gmock-all.cc:39:
 ../../../Tools/googletest/googlemock/src/gmock.cc: In instantiation of 'void testing::internal::InitGoogleMockImpl(int*, CharType**) [with CharType = wchar_t]':
 ../../../Tools/googletest/googlemock/src/gmock.cc:198:42:   required from here
 ../../../Tools/googletest/googlemock/include/gmock/internal/gmock-port.h:67:26: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
    67 | #define GMOCK_FLAG(name) FLAGS_gmock_##name
       |                          ^~~~~~~~~~~~
       |                          |
       |                          int32_t* {aka long int*}
 ../../../Tools/googletest/googlemock/src/gmock.cc:159:33: note: in expansion of macro 'GMOCK_FLAG'
   159 |                                &GMOCK_FLAG(default_mock_behavior))) {
       |                                 ^~~~~~~~~~
 In file included from ../../../Tools/googletest/googlemock/src/gmock-all.cc:46:
 ../../../Tools/googletest/googlemock/src/gmock.cc:127:41: note:   initializing argument 3 of 'bool testing::internal::ParseGoogleMockIntFlag(const char*, const char*, int*)'
   127 |                                    int* value) {
       |                                    ~~~~~^~~~~
 make: *** [out-arm/obj/gmock-all.o] Error 1
```

**Comment by NINI1988** [comment]
After updating GoogleTest to v1.13 and compiling with `-std=gnu++14` the problem is gone.
