### ISSUE TITLE
Compilation errors with MinGW 6.3 + MSYS + cmake 3.13.1

### ISSUE THREAD

**Issue by vladislavmarkov** [google/googletest#2011]
Works on v1.8.x.
But on master I get the following compilation error:

$ cmake -G "MSYS Makefiles" -Dgtest_disable_pthreads=ON ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/msys/1.0/googletest/build

$ make
Scanning dependencies of target gtest
[ 12%] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj
In file included from C:/msys/1.0/googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/msys/1.0/googletest/googletest/include/gtest/gtest.h:60,
                 from c:/msys/1.0/googletest/googletest/src/gtest-all.cc:38:
C:/msys/1.0/googletest/googletest/include/gtest/internal/gtest-port.h: In function 'int testing::internal::posix::StrCaseCmp(const char*, const char*)':
C:/msys/1.0/googletest/googletest/include/gtest/internal/gtest-port.h:2215:25: error: '_stricmp' was not declared in this scope
   return _stricmp(s1, s2);
                         ^
C:/msys/1.0/googletest/googletest/include/gtest/internal/gtest-port.h: In function 'char* testing::internal::posix::StrDup(const char*)':
C:/msys/1.0/googletest/googletest/include/gtest/internal/gtest-port.h:2217:58: error: '_strdup' was not declared in this scope
 inline char* StrDup(const char* src) { return _strdup(src); }
                                                          ^
C:/msys/1.0/googletest/googletest/include/gtest/internal/gtest-port.h: In function 'int testing::internal::posix::FileNo(FILE*)':
C:/msys/1.0/googletest/googletest/include/gtest/internal/gtest-port.h:2225:52: error: '_fileno' was not declared in this scope
 inline int FileNo(FILE* file) { return _fileno(file); }
                                                    ^
C:/msys/1.0/googletest/googletest/include/gtest/internal/gtest-port.h: In function 'FILE* testing::internal::posix::FDOpen(int, const char*)':
C:/msys/1.0/googletest/googletest/include/gtest/internal/gtest-port.h:2271:71: error: 'fdopen' was not declared in this scope
 inline FILE* FDOpen(int fd, const char* mode) { return fdopen(fd, mode); }
                                                                       ^
In file included from c:/msys/1.0/googletest/googletest/src/gtest-all.cc:41:0:
C:/msys/1.0/googletest/googletest/src/gtest.cc: In static member function 'static bool testing::internal::String::CaseInsensitiveWideCStringEquals(const wchar_t*, const wchar_t*)':
C:/msys/1.0/googletest/googletest/src/gtest.cc:1971:27: error: '_wcsicmp' was not declared in this scope
   return _wcsicmp(lhs, rhs) == 0;
                           ^
C:/msys/1.0/googletest/googletest/src/gtest.cc: In member function 'int testing::UnitTest::Run()':
C:/msys/1.0/googletest/googletest/src/gtest.cc:4805:21: error: '_OUT_TO_STDERR' was not declared in this scope
     _set_error_mode(_OUT_TO_STDERR);
                     ^~~~~~~~~~~~~~
C:/msys/1.0/googletest/googletest/src/gtest.cc:4805:35: error: '_set_error_mode' was not declared in this scope
     _set_error_mode(_OUT_TO_STDERR);
                                   ^
In file included from c:/msys/1.0/googletest/googletest/src/gtest-all.cc:42:0:
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc: In function 'void testing::internal::DeathTestAbort(const string&)':
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc:297:12: error: '_exit' was not declared in this scope
     _exit(1);
            ^
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc: In member function 'virtual void testing::internal::DeathTestImpl::Abort(testing::internal::DeathTest::AbortReason)':
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc:528:10: error: '_exit' was not declared in this scope
   _exit(1);  // Exits w/o any normal exit hooks (we were supposed to crash)
          ^
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc: In member function 'virtual testing::internal::DeathTest::TestRole testing::internal::WindowsDeathTest::AssumeRole()':
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc:772:24: error: '_MAX_PATH' was not declared in this scope
   char executable_path[_MAX_PATH + 1];  // NOLINT
                        ^~~~~~~~~
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc:774:65: error: 'executable_path' was not declared in this scope
                                                                 executable_path,
                                                                 ^
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc:309:38: note: in definition of macro 'GTEST_DEATH_TEST_CHECK_'
     if (!::testing::internal::IsTrue(expression)) { \
                                      ^~~~~~~~~~
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc:798:11: error: 'executable_path' was not declared in this scope
           executable_path, const_cast<char*>(command_line.c_str()),
           ^
C:/msys/1.0/googletest/googletest/src/gtest-death-test.cc:309:38: note: in definition of macro 'GTEST_DEATH_TEST_CHECK_'
     if (!::testing::internal::IsTrue(expression)) { \
                                      ^~~~~~~~~~
In file included from c:/msys/1.0/googletest/googletest/src/gtest-all.cc:43:0:
C:/msys/1.0/googletest/googletest/src/gtest-filepath.cc: In static member function 'static testing::internal::FilePath testing::internal::FilePath::GetCurrentDir()':
C:/msys/1.0/googletest/googletest/src/gtest-filepath.cc:52:26: error: '_MAX_PATH' was not declared in this scope
 # define GTEST_PATH_MAX_ _MAX_PATH
                          ^
C:/msys/1.0/googletest/googletest/src/gtest-filepath.cc:103:12: note: in expansion of macro 'GTEST_PATH_MAX_'
   char cwd[GTEST_PATH_MAX_ + 1] = { '\0' };
            ^~~~~~~~~~~~~~~
C:/msys/1.0/googletest/googletest/src/gtest-filepath.cc:104:27: error: 'cwd' was not declared in this scope
   return FilePath(_getcwd(cwd, sizeof(cwd)) == nullptr ? "" : cwd);
                           ^~~
make[2]: *** [googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj] Error 1
make[1]: *** [googlemock/gtest/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2

**Comment by gennadiycivil** [comment]
Thank you very much for this report. The best way to approach this would be to create a proper PR and submit it for consideration.

**Comment by gennadiycivil** [comment]
ping
