### ISSUE TITLE
fail to compile on Linux with MinGW 4.8.2

### ISSUE THREAD

**Issue by dneto0** [google/googletest#858]
Caused by https://github.com/google/googletest/commit/ed9d1e1ff92ce199de5ca2667a667cd0a368482a which is a merge of #721 

I get errors such as:
```
gtest-port.cc:242:45: error: cannot convert ‘CRITICAL_SECTION* {aka _RTL_CRITICAL_SECTION*}’ to ‘GTEST_CRITICAL_SECTION* {aka _CRITICAL_SECTION*}’ in initialization
       critical_section_(new CRITICAL_SECTION) {
                                             ^
```

The host platform is Ubuntu with MinGW 4.8.2.

I've configured the project as follows:
```
cmake -GNinja -Dgtest_disable_pthreads=ON DCMAKE_BUILD_TYPE=RelWithDebInfo 
-DCMAKE_TOOLCHAIN_FILE=linux-mingw-toolchain.cmake ../googletest
```

Where toolchain.cmake is https://github.com/google/shaderc/blob/master/cmake/linux-mingw-toolchain.cmake or:
```
SET(CMAKE_SYSTEM_NAME Windows)

set(MINGW_COMPILER_PREFIX "i686-w64-mingw32" CACHE STRING
    "What compiler prefix to use for mingw")

set(MINGW_SYSROOT "/usr/${MINGW_COMPILER_PREFIX}" CACHE STRING
    "What sysroot to use for mingw")

# Which compilers to use for C and C++
find_program(CMAKE_RC_COMPILER NAMES ${MINGW_COMPILER_PREFIX}-windres)
find_program(CMAKE_C_COMPILER NAMES ${MINGW_COMPILER_PREFIX}-gcc)
find_program(CMAKE_CXX_COMPILER NAMES ${MINGW_COMPILER_PREFIX}-g++)

SET(CMAKE_FIND_ROOT_PATH ${MINGW_SYSROOT})

# Adjust the default behaviour of the FIND_XXX() commands:
# Search headers and libraries in the target environment; search
# programs in the host environment.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

**Comment by dneto0** [comment]
In my situation, GTEST_OS_WINDOWS_MINGW is true and so we get the definition of GTEST_CRITICAL_SECTION from
https://github.com/google/googletest/blob/master/googletest/include/gtest/internal/gtest-port.h#L402

But that's wrong for MinGW 4.8.2, it seems.  (I would guess it's not dependent on the fact I'm on Linux.)

**Comment by KindDragon** [comment]
Fixed in PR #856

**Comment by KindDragon** [comment]
Can you try with this changes https://github.com/google/googletest/pull/856 ?

**Comment by dneto0** [comment]
@KindDragon Yes, your patch fixes this compilation problem.  My test executable both compiles and passes its tests when targeting both 32 and 64 bit codes.  That is, it works with both i686-w64-mingw-g++ and x86_66-w64-mingw-g++
Thanks!

**Comment by dneto0** [comment]
The merge of #856 fixed this for me.
