### ISSUE TITLE
EXPECT_THROW compile error when using function templates with multiple template arguments

### ISSUE THREAD

**Issue by Tohnmeister** [google/googletest#3803]
**Describe the bug**

I have a function that takes two template arguments and could possibly throw. I want to check that that functions throws in certain situations. When using `EXPECT_THROW` though, I'm getting compile errors.

See steps to reproduce for the exact code. Basically whenever using `EXPECT_THROW` on a function or a class method that takes two template arguments, but no parameters, the code fails to compile. I expect it to compile.

Also tried with gtest/1.11.0. Slightly different errors, but still fails to compile.

**Steps to reproduce the bug**

```c++
#include "gtest/gtest.h"
#include <exception>

namespace {

class Foobar {
public:
	template <typename T, typename U>
	void myFunc1() {
	}

	void myFunc2() {
	}
};

template <typename T, typename U>
void myFunc() {
}

TEST(FoobarTest, ShowExpectThrowIssue) {
	Foobar foobar;

        // Compile error
	EXPECT_THROW(foobar.myFunc1<int, int>(), std::exception);

        // This line does compile
	EXPECT_THROW(foobar.myFunc2(), std::exception);

        // Compile error
	EXPECT_THROW(myFunc<int, int>(), std::exception);
}

}
```

The above code does not compile with and generates the following errors:

```
1>myfile.cpp(249): error C2059: syntax error: ';'
1>myfile.cpp(249): error C2143: syntax error: missing ';' before '}'
1>myfile.cpp(249): error C2947: expecting '>' to terminate template-argument-list, found '>'
1>myfile.cpp(249): error C2059: syntax error: ')'
1>myfile.cpp(249): error C2318: no try block associated with this catch handler
1>myfile.cpp(249): error C2317: 'try' block starting on line '249' has no catch handlers
1>myfile.cpp(249): error C2181: illegal else without matching if
1>myfile.cpp(253): fatal error C1004: unexpected end-of-file found
```

**What operating system and version are you using?**

Windows 10

gtest/1.10.0

**What compiler and version are you using?**

MSVC 14.16.27023

**What build system are you using?**

Visual Studio 2022/MSBuild

**Additional context**

Can workaround the problem by wrapping the call to the function in another function. Seems to be related only to functions that take more than on template arguments and when specifying the template arguments explicitly.

**Comment by Anucha7736zxc** [comment]
Describe the bug

Include a clear and concise description of what the problem is, including what
you expected to happen, and what actually happened.

Showing All Issues
Ignoring file /Users/walle.fu/.conan/data/googletest/1.8.1/mthor/stable/package/105876dec92f9a83153bf5fcecc0fc2571d7ba2f/lib/libgtest.a, file is universal (x86_64) but does not contain the arm64 architecture: /Users/walle.fu/.conan/data/googletest/1.8.1/mthor/stable/package/105876dec92f9a83153bf5fcecc0fc2571d7ba2f/lib/libgtest.a

Undefined symbol: testing::InitGoogleTest(int*, char**)

Undefined symbol: testing::AssertionResult::AssertionResult(testing::AssertionResult const&)

Undefined symbol: testing::AssertionFailure()

Undefined symbol: testing::AssertionSuccess()

Undefined symbol: testing::Test::Test()

Undefined symbol: testing::Test::~Test()

Undefined symbol: testing::Message::Message()

Undefined symbol: testing::UnitTest::GetInstance()

Undefined symbol: testing::UnitTest::AddEnvironment(testing::Environment*)

Undefined symbol: testing::UnitTest::Run()

Undefined symbol: testing::internal::CmpHelperEQ(char const*, char const*, long long, long long)

Undefined symbol: testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)

Undefined symbol: testing::internal::AssertHelper::~AssertHelper()

Undefined symbol: testing::internal::PrintStringTo(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::basic_ostream<char, std::__1::char_traits >*)

Undefined symbol: testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void ()(), void ()(), testing::internal::TestFactoryBase*)

Undefined symbol: testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)

Undefined symbol: testing::internal::IsTrue(bool)

Undefined symbol: testing::internal::EqFailure(char const*, char const*, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, bool)

Undefined symbol: testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::__1::basic_ostream<char, std::__1::char_traits >*)

Undefined symbol: testing::Message::GetString() const

Undefined symbol: testing::internal::AssertHelper::operator=(testing::Message const&) const

Undefined symbol: typeinfo for testing::Test

Steps to reproduce the bug

It's important that we are able to reproduce the problem that you are
experiencing. Please provide all code and relevant steps to reproduce the
problem, including your BUILD/CMakeLists.txt file and build commands. Links
to a GitHub branch or godbolt.org that demonstrate the
problem are also helpful.

Does the bug persist in the most recent commit?

We recommend using the latest commit in the master branch in your projects.

What operating system and version are you using?
MAC pro 2021

If you are using a Linux distribution please include the name and version of the
distribution as well.

What compiler and version are you using?
Clang 13
Xcode 13.3.1

Please include the output of gcc -v or clang -v, or the equivalent for your
compiler.

What build system are you using?
Mac OS 12.3.1

Please include the output of bazel --version or cmake --version, or the
equivalent for your build system.

Additional context

Add any other context about the problem here.

**Comment by Anucha7736zxc** [comment]
1>myfile.cpp(249): error C2059: syntax error: ';'
1>myfile.cpp(249): error C2143: syntax error: missing ';' before '}'
1>myfile.cpp(249): error C2947: expecting '>' to terminate
template-argument-list, found '>'
1>myfile.cpp(249): error C2059: syntax error: ')'
1>myfile.cpp(249): error C2318: no try block associated with this catch
handler
1>myfile.cpp(249): error C2317: 'try' block starting on line '249' has no
catch handlers
1>myfile.cpp(249): error C2181: illegal else without matching if
1>myfile.cpp(253): fatal error C1004: unexpected end-of-file found#include
"gtest/gtest.h"

namespace {

class Foobar {
public:
 template <typename T, typename U>
 void myFunc1() {
 }

 void myFunc2() {
 }
};

template <typename T, typename U>
void myFunc() {
}

TEST(FoobarTest, ShowExpectThrowIssue) {
 Foobar foobar;

 EXPECT_THROW(foobar.myFunc1<int, int>(), std::exception);
 EXPECT_THROW(foobar.myFunc2(), std::exception);
 EXPECT_THROW(myFunc<int, int>(), std::exception);
}

}

ในวันที่ ศ. 22 เม.ย. 2022 15:09 น. Tonni Tielens ***@***.***>
เขียนว่า:

**Comment by apcountryman** [comment]
The comma in the template argument list results in the preprocessor thinking that `EXPECT_THROW()` is being passed 3 arguments when it only takes two. Wrapping the first argument to `EXPECT_THROW()` in parenthesis should fix this (works with gcc 9.4.0 which also gave much clearer error messages):
```c++
EXPECT_THROW((foobar.myFunc1<int, int>()), std::exception);
```
```c++
EXPECT_THROW((myFunc<int, int>()), std::exception);
```

**Comment by Tohnmeister** [comment]
> The comma in the template argument list results in the preprocessor thinking that `EXPECT_THROW()` is being passed 3 arguments when it only takes two. Wrapping the first argument to `EXPECT_THROW()` in parenthesis should fix this (works with gcc 9.4.0 which also gave much clearer error messages):
> 
> ```c++
> EXPECT_THROW((foobar.myFunc1<int, int>()), std::exception);
> ```
> 
> ```c++
> EXPECT_THROW((myFunc<int, int>()), std::exception);
> ```

Thanks a lot!

**Comment by Tohnmeister** [comment]
Wrapping in parenthesis as suggested by [here](https://github.com/google/googletest/issues/3803#issuecomment-1106666326) works. Thanks @apcountryman.

**Comment by eric-silk** [comment]
Not to necro an old issue, but would is this listed in the documentation anywhere as a "gotcha"? I just spent an afternoon chasing my tail on this exact issue, believing it to be a google test issue rather than a macro issue. If it's not, I'll open an issue to add it. Thanks!
