### ISSUE TITLE
CLang error compiling ASSERT_FALSE(false)

### ISSUE THREAD

**Issue by skypjack** [google/googletest#780]
I compiled `googletest` in a subdirectory named `build` and everything went fine.
Then I tried to compile the following code:

    #include <gtest/gtest.h>
    TEST(FOO, BAR) { ASSERT_FALSE(false); }

It compiles fine with GCC (v5.3.1) using the following command:

    g++ -L./googletest/build/googlemock/gtest -L./googletest/build/googlemock -I./googletest/googletest/include/ -lgmock -lgtest -lgtest_main -lgmock_main -pthread -std=c++11 main.cpp

Anyway, it does not compile with clang (v3.6.2) using almost the same command:

    clang++ -L./googletest/build/googlemock/gtest -L./googletest/build/googlemock -I./googletest/googletest/include/ -lgmock -lgtest -lgtest_main -lgmock_main -pthread -std=c++11 main.cpp

The error is the following one:

> /tmp/main-4127ae.o: In function 'FOO_BAR_Test::TestBody()':
> main.cpp:(.text+0x7b): undefined reference to `testing::internal::GetBoolAssertionFailureMessage(testing::AssertionResult const&, char const*, char const*, char const*)'
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

The same applies for `ASSERT_TRUE`.

**Comment by skypjack** [comment]
ABI related issue.
