### ISSUE TITLE
Unable to compile tests which use exception assertions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/googletest#418]
```
The issue has been posted in googletestframework without being replied, so I 
post it here as well.

https://groups.google.com/d/topic/googletestframework/D3OqJspi2TI/discussion

If you really need to create a new issue, please provide the information
asked for below.

What steps will reproduce the problem?
1. Create a test file that is using either of: ASSERT_THROW, ASSERT_ANY_THROW, 
ASSERT_NO_THROW, EXPECT_THROW, EXPECT_ANY_THROW, EXPECT_NO_THROW.
For example use this:

#include "gtest/gtest.h"

TEST(Tests, NoThrowTest) {
     EXPECT_NO_THROW({ int i = 1; });
}

2. Compile with VC7.1 (Microsoft Visual Studio .NET 2003)


What is the expected output? What do you see instead?
I expect the compilation to succeed. Instead, I get compilation error:

------ Build started: Project: Unit_tests, Configuration: Debug Win32 ------

Compiling...

tcp_ip_tests.cpp

d:\Projects\Diamond_0_1\diamond_0.1_integ\hwctrl\test\src\core\communication\tcp
_ip\tcp_ip_tests.cpp(4) : error C2143: syntax error : missing ';' before '('

d:\Projects\Diamond_0_1\diamond_0.1_integ\hwctrl\test\src\core\communication\tcp
_ip\tcp_ip_tests.cpp(4) : error C2143: syntax error : missing ';' before ':'

d:\Projects\Diamond_0_1\diamond_0.1_integ\hwctrl\test\src\core\communication\tcp
_ip\tcp_ip_tests.cpp(4) : error C3861: 'gtest_label_testnothrow_': identifier 
not found, even with argument-dependent lookup

d:\Projects\Diamond_0_1\diamond_0.1_integ\hwctrl\test\src\core\communication\tcp
_ip\tcp_ip_tests.cpp(4) : error C2143: syntax error : missing ';' before ':'



What version of Google Test are you using? 
I use google test version 1.6

On what operating system?
Windows 7

Please provide any additional information below, such as a code snippet.
The compilation problem shows only when using exception assertions. Without 
them it compiles and runs as expected.

```

Original issue reported on code.google.com by `YalonLo...@gmail.com` on 4 Sep 2012 at 11:57
