### ISSUE TITLE
Does not compile with C++17 (with MSVC2017 15.8.1)

### ISSUE THREAD

**Issue by csware** [google/googletest#1788]
Compilation with C++17 with MSVC2017 (15.8.1) fails (as of 1d9a1912e7f42e8ae66ea365b5b8508fecb31509):

> googletest\googletest\include\gtest\gtest-printers.h(250): error C2593: "Operator <<" is ambiguous
> 42>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.15.26726\include\ostream(502): note: can be "std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<<void>(std::nullptr_t)"
> 42>googletest\googletest\include\gtest\gtest-printers.h(204): note: or "std::basic_ostream<char,std::char_traits<char>> &testing::internal2::operator <<<char,std::char_traits<char>,T>(std::basic_ostream<char,std::char_traits<char>> &,const T &)"
> 42>        with
> 42>        [
> 42>            T=T1
> 42>        ]
> ...

**Comment by staffantj** [comment]
+1 
This issue is specific to testing for equality / inequality with nullptr. 
We have worked around with
`ASSERT_FALSE( nullptr == test_value );`
I think you have only captured the first part of the error message, in that the important part is the very end which talks about a problem with resolving the _is_string_view_ish trait defined in xtring line 2121 or thereabouts if memory serves.

**Comment by csware** [comment]
I'm sorry. The error message was not complete - I trucated it because I only have German error messages and did not want to want to translate everything manually.

**Comment by staffantj** [comment]
Not a problem - I've found what I believe to be half the root cause.

The new STL that came with MSVC 2017.15.8.0 includes the following specialization for nulltpr_t in `<ostream>`

`#if _HAS_CXX17 // LWG 2221 "No formatted output operator for nullptr"
	template<class = void>	// TRANSITION, ABI
		basic_ostream& operator<<(nullptr_t)
		{	// insert a null pointer
		return (*this << "nullptr");
		}
#endif // _HAS_CXX17`

gtest-printers.h has the following comment that seems germane.

```
// Note that this operator<< takes a generic std::basic_ostream<Char,
// CharTraits> type instead of the more restricted std::ostream.  If
// we define it to take an std::ostream instead, we'll get an
// "ambiguous overloads" compiler error when trying to print a type
// Foo that supports streaming to std::basic_ostream<Char,
// CharTraits>, as the compiler cannot tell whether
// operator<<(std::ostream&, const T&) or
// operator<<(std::basic_stream<Char, CharTraits>, const Foo&) is more
// specific.
template <typename Char, typename CharTraits, typename T>
::std::basic_ostream<Char, CharTraits>& operator<<(
    ::std::basic_ostream<Char, CharTraits>& os, const T& x) {
  TypeWithoutFormatter<T, (internal::IsAProtocolMessage<T>::value
                               ? kProtobuf
                               : internal::ImplicitlyConvertible<
                                     const T&, internal::BiggestInt>::value
                                     ? kConvertibleToInteger
                                     :
#if GTEST_HAS_ABSL
                                     internal::ImplicitlyConvertible<
                                         const T&, absl::string_view>::value
                                         ? kConvertibleToStringView
                                         :
#endif
                                         kOtherType)>::PrintValue(x, &os);
  return os;
}
```
This is obviously high-value internals of gtest, and I'm unfamiliar enough with the code that I'm not in a good position to suggest a fix, other than maybe SFINAEing away the testing2:: definition in the case of T being nullptr when compiled under Visual Studio (since presumably this is not an issue with libstdc++ / libc++ ).
