### ISSUE TITLE
EXPECT_EQ compile errors with MSVC /Za (Disable Language Extensions)

### ISSUE THREAD

**Issue by enterid** [google/googletest#2336]
The following code produces errors if MSVC /Za flag (Disable Language Extensions) is set:
`#include <gtest/gtest.h>  

struct T
{
	bool operator==(const T& rhs) const noexcept
	{
		return a == rhs.a;
	}
	int a;
};

enum class Test { a, b, c};

int main()
{
	const Test t1{ Test::a };
	const Test t2{ Test::a };
	EXPECT_EQ(t1, t2);
 
	const T t3{1};
	const T t4{1};
	EXPECT_EQ(t3, t4);
}
`

Both EXPECT_EQ are failing to compile:
error C2664: 'testing::AssertionResult testing::internal::EqHelper::Compare(const char *,const char *,testing::internal::BiggestInt,testing::internal::BiggestInt)': cannot convert argument 3 from 'const Test' to 'testing::internal::BiggestInt'
error C2512: 'testing::AssertionResult': no appropriate default constructor available

Checked with MSVC 2017 (15.9.11) and googletest master (rev. f899e81).

**Comment by kuzkry** [comment]
This piece of code compiles on g++ 7.4.0 and clang++ 6.0.0 with `-std=c++17 -Wall -Wextra -pedantic` flags enabled for both. I suppose it's a compiler-specific problem.

**Comment by enterid** [comment]
Yes, this code compiles with clang and gcc, but I would like to get a confirmation that internally googletest is not using any compiler specific things, only then I can report this to MSVC.

**Comment by kuzkry** [comment]
I'm neither a build system nor MSVC expert, but I've found some interesting [commands](https://github.com/google/googletest/blob/f899e81e43407c9a3433d9ad3a0a8f64e450ba44/googletest/cmake/internal_utils.cmake#L71) which seems to overwrite default flags set by CMake by a bunch of flags for MSVC. Perhaps you might wanna check it out.
Please note, this is just my guess. I cannot really check & confirm it as my machine doesn't run Windows.

**Comment by gennadiycivil** [comment]
@enterid 

> Yes, this code compiles with clang and gcc, but I would like to get a confirmation that internally googletest is not using any compiler specific things, only then I can report this to MSVC.

Looks straighforward enough for me. In addition we have CI set with MCVS - see here https://github.com/google/googletest/blob/f899e81e43407c9a3433d9ad3a0a8f64e450ba44/appveyor.yml#L3 which compiles and runs with no issues.

I would suggest trying to add this version of MSVC to the build matrix and see what happens

**Comment by enterid** [comment]
The problem occurs only with /Za flag enabled. It looks like that this overload from EqHelper gets ignored:
`  template <
      typename T1, typename T2,
      // Disable this overload for cases where one argument is a pointer
      // and the other is the null pointer constant.
      typename std::enable_if<!std::is_integral<T1>::value ||
                              !std::is_pointer<T2>::value>::type* = nullptr>
  static AssertionResult Compare(const char* lhs_expression,
                                 const char* rhs_expression, const T1& lhs,
                                 const T2& rhs) {
    return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
  }`

and gtest fallbacks to 
`GTEST_API_ AssertionResult CmpHelperEQ(const char* lhs_expression,
                                       const char* rhs_expression,
                                       BiggestInt lhs,
                                       BiggestInt rhs);`

Looks like MSVC /Za does not like std:enable_if part, if I change it from a non-type template parameter:
`typename std::enable_if<!std::is_integral<T1>::value ||
                                    !std::is_pointer<T2>::value>::type* =
               nullptr`

to a type template parameter:
`typename = std::enable_if<!std::is_integral<T1>::value ||
                                      !std::is_pointer<T2>::value>::type`

then everything is ok.

**Comment by kuzkry** [comment]
Nice deduction @enterid. Then, to simplify what you were saying:
```c++
template <void* = nullptr>
void foo1() {} // NOT GOOD

template <typename = void*>
void foo2() {} // GOOD
```

But then, even if you report it to MSVC, they will probably tell you this:
> In C++ compilation mode, the /Za option may cause unexpected behavior and isn't recommended.

Since it doesn't matter for us (we're only SFINAEing on this), I guess you can try to submit a pull request.

**Comment by enterid** [comment]
@kuzkry thanks for pointing me to a /Za limitation. Since this is C++standard conformant code I would prefer to leave it as it is.
