### ISSUE TITLE
Link error caused by undefined reference

### ISSUE THREAD

**Issue by offa** [google/googletest#1949]
After updating to the latest `master` (71d4fc8d76ebd539440aff5cfc873be9b50f202b) my tests fail to link because of undefined references:

```
undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
```
The problem occurs with GCC and Clang.

Tests link following parts of GTest / GMock:

- libgtest
- libgmock
- libgtest_main

I have tested with a full rebuild (clean and build) of both – GTest / GMock and my tests – but this doesn't solve the problem.

#### Excerpt of the error:
```
/usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<int (libusb_context**)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_context**> > const&)':
[…]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
/usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<libusb_device_handle* (libusb_context*, unsigned short, unsigned short)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_context*>, testing::Matcher<unsigned short>, testing::Matcher<unsigned short> > const&)':
[…]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
/usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<int (libusb_device_handle*, int)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_device_handle*>, testing::Matcher<int> > const&)':
[…]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
/usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<int (libusb_device_handle*, unsigned char, unsigned char*, int, int*, unsigned int)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_device_handle*>, testing::Matcher<unsigned char>, testing::Matcher<unsigned char*>, testing::Matcher<int>, testing::Matcher<int*>, testing::Matcher<unsigned int> > const&)':
[…]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
/usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<void (libusb_device_handle*)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_device_handle*> > const&)':
[…]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
/usr/bin/ld: […]/MustangTest.cpp.o:[…]/gmock/gmock-spec-builders.h:1633: more undefined references to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)' follow
```
According to bisect the issue was introduced with 80b43d900b8ed44e16b306682d47d73175cecc7f.

### System
- GTest / GMock `master` (71d4fc8d76ebd539440aff5cfc873be9b50f202b)
- Linux
- CMake 3.12.3
- GCC 8.2.1 / Clang 7.0.0

**Comment by sbenzaquen** [comment]
On Wed, Oct 31, 2018 at 1:14 PM offa <notifications@github.com> wrote:

> After updating to the latest master (71d4fc8
> <https://github.com/google/googletest/commit/71d4fc8d76ebd539440aff5cfc873be9b50f202b>)
> my tests fail to link because of undefined references:
>
> undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
>
> The problem occurs with GCC and Clang.
>
> Tests link following parts of GTest / GMock:
>
>    - libgtest
>    - libgmock
>    - libgtest_main
>
> I have tested with a full rebuild (clean and build) of both – GTest /
> GMock and my tests – but this doesn't solve the problem.
> Excerpt of the error:
>
> /usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<int (libusb_context**)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_context**> > const&)':
> […]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
> /usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<libusb_device_handle* (libusb_context*, unsigned short, unsigned short)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_context*>, testing::Matcher<unsigned short>, testing::Matcher<unsigned short> > const&)':
> […]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
> /usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<int (libusb_device_handle*, int)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_device_handle*>, testing::Matcher<int> > const&)':
> […]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
> /usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<int (libusb_device_handle*, unsigned char, unsigned char*, int, int*, unsigned int)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_device_handle*>, testing::Matcher<unsigned char>, testing::Matcher<unsigned char*>, testing::Matcher<int>, testing::Matcher<int*>, testing::Matcher<unsigned int> > const&)':
> […]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
> /usr/bin/ld: […]/MustangTest.cpp.o: in function `testing::internal::FunctionMockerBase<void (libusb_device_handle*)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tuple<testing::Matcher<libusb_device_handle*> > const&)':
> […]/gmock/gmock-spec-builders.h:1633: undefined reference to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)'
> /usr/bin/ld: […]/MustangTest.cpp.o:[…]/gmock/gmock-spec-builders.h:1633: more undefined references to `testing::Expectation::Expectation(std::shared_ptr<testing::internal::ExpectationBase> const&)' follow
>
> According to bisect the issue was introduced with 80b43d9
> <https://github.com/google/googletest/commit/80b43d900b8ed44e16b306682d47d73175cecc7f>
> .
>
Are you sure you are compiling the latest .cc files from googletest/... ?
That error seems like you are using the latest header but linking against
an older version of the lib.
Note that  80b43d9
<https://github.com/google/googletest/commit/80b43d900b8ed44e16b306682d47d73175cecc7f>
changed
both the declaration in the header and the definition in the .cc file for
that constructor.
Also make sure that everything is built with the same compiler options,
including standard library. Otherwise you might have problems like this
because one library uses a different ABI than another.

**Comment by offa** [comment]
Yes, I've made a clean build with same same compiler as I use for the tests. I also can checkout an earlier version (somewhere prior to the mentioned commit) and it works; going back to master or any other commit after the broken one reproducibly fails.

But to be sure, I'll remove the build directories (incl. Cmake cache etc.) of all projects involved and completely build everything from scratch. I also disable Sanitizer or LTO everywhere.

**Comment by offa** [comment]
I finally figured out, what caused my issue: There was an another version of gmock installed on my system which got picked up instead of the updated one. Removing the other installation finally fixed it.
