### ISSUE TITLE
Build errors on MinGW 5.3

### ISSUE THREAD

**Issue by comargo** [google/googletest#831]
Build errors when trying to build with MinGW 5.3.0

Main excerpts:
``

> g++ --version
> g++ (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.3.0
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> mingw32-make
> [  0%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj
> In file included from C:/Users/Cyril/Projects/googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
>                  from C:/Users/Cyril/Projects/googletest/googletest/include/gtest/gtest.h:58,
>                  from C:\Users\Cyril\Projects\googletest\googletest\src\gtest-all.cc:39:
> C:/Users/Cyril/Projects/googletest/googletest/include/gtest/internal/gtest-port.h:1782:3: error: 'AutoHandle' does not name a type
>    AutoHandle thread_;
>    ^
> -=-=-=-=-=-=-=-=-
> In file included from C:\Users\Cyril\Projects\googletest\googletest\src\gtest-all.cc:45:0:
> C:/Users/Cyril/Projects/googletest/googletest/src/gtest-port.cc: In function 'void testing::internal::SleepMilliseconds(int)':
> C:/Users/Cyril/Projects/googletest/googletest/src/gtest-port.cc:179:6: error: redefinition of 'void testing::internal::SleepMilliseconds(int)'
>  void SleepMilliseconds(int n) {
>       ^
> In file included from C:/Users/Cyril/Projects/googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
>                  from C:/Users/Cyril/Projects/googletest/googletest/include/gtest/gtest.h:58,
>                  from C:\Users\Cyril\Projects\googletest\googletest\src\gtest-all.cc:39:
> C:/Users/Cyril/Projects/googletest/googletest/include/gtest/internal/gtest-port.h:1448:13: note: 'void testing::internal::SleepMilliseconds(int)' previously defined here
>  inline void SleepMilliseconds(int n) {
>              ^
> ``
