### PR TITLE
Fix compilation of googletest with MinGW using Win32 threads

### LINKED ISSUE #708: GTest not compiling
Hello,
today i wanted to use gtest with my eclipse / mingw makefile project.
On my machine(Win7) is a working mingw toolchain installed.
I followed the instructions on 

> http://www.codeproject.com/Articles/811934/Cplusplus-unit-test-start-guide-how-to-set-up-Goog

to set up gtest. But when i try to run the tests i get the following errors:
```
Info: Internal Builder is used for build
g++ "-IC:\\Users\\XXX\\eclipse_playground_workspace\\unitttest\\include" "-IC:\\Users\\XXX\\eclipse_playground_workspace\\unitttest\\gtest_src" -O0 -g3 -Wall -c -fmessage-length=0 -o "test\\gtest_main.o" "..\\test\\gtest_main.cpp" 
g++ "-IC:\\Users\\XXX\\eclipse_playground_workspace\\unitttest\\include" "-IC:\\Users\\XXX\\eclipse_playground_workspace\\unitttest\\gtest_src" -O0 -g3 -Wall -c -fmessage-length=0 -o "test\\test_factorial.o" "..\\test\\test_factorial.cpp" 
g++ -O0 -g3 -Wall -c -fmessage-length=0 -o "src\\factorial.o" "..\\src\\factorial.cpp" 
g++ "-IC:\\Users\\XXX\\eclipse_playground_workspace\\unitttest\\gtest_src" -O0 -g3 -Wall -c -fmessage-length=0 -o "gtest_src\\gtest\\gtest-all.o" "..\\gtest_src\\gtest\\gtest-all.cc" 
..\gtest_src\gtest\gtest-all.cc: In constructor 'testing::internal::Mutex::Mutex()':
..\gtest_src\gtest\gtest-all.cc:8791:45: error: cannot convert 'CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to '_RTL_CRITICAL_SECTION*' in initialization
       critical_section_(new CRITICAL_SECTION) {
                                             ^
..\gtest_src\gtest\gtest-all.cc:8792:48: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void InitializeCriticalSection(LPCRITICAL_SECTION)'
   ::InitializeCriticalSection(critical_section_);
                                                ^
..\gtest_src\gtest\gtest-all.cc: In destructor 'testing::internal::Mutex::~Mutex()':
..\gtest_src\gtest\gtest-all.cc:8802:46: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'PCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void DeleteCriticalSection(PCRITICAL_SECTION)'
     ::DeleteCriticalSection(critical_section_);
                                              ^
..\gtest_src\gtest\gtest-all.cc: In member function 'void testing::internal::Mutex::Lock()':
..\gtest_src\gtest\gtest-all.cc:8810:43: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void EnterCriticalSection(LPCRITICAL_SECTION)'
   ::EnterCriticalSection(critical_section_);
                                           ^
..\gtest_src\gtest\gtest-all.cc: In member function 'void testing::internal::Mutex::Unlock()':
..\gtest_src\gtest\gtest-all.cc:8820:43: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void LeaveCriticalSection(LPCRITICAL_SECTION)'
   ::LeaveCriticalSection(critical_section_);
                                           ^
..\gtest_src\gtest\gtest-all.cc: In member function 'void testing::internal::Mutex::ThreadSafeLazyInit()':
..\gtest_src\gtest\gtest-all.cc:8841:27: error: cannot convert 'CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to '_RTL_CRITICAL_SECTION*' in assignment
         critical_section_ = new CRITICAL_SECTION;
                           ^
..\gtest_src\gtest\gtest-all.cc:8842:54: error: cannot convert '_RTL_CRITICAL_SECTION*' to 'LPCRITICAL_SECTION {aka _CRITICAL_SECTION*}' for argument '1' to 'void InitializeCriticalSection(LPCRITICAL_SECTION)'
         ::InitializeCriticalSection(critical_section_);
                                                      ^
..\gtest_src\gtest\gtest-all.cc: In static member function 'static void testing::internal::ThreadLocalRegistryImpl::StartWatcherThreadFor(DWORD)':
..\gtest_src\gtest\gtest-all.cc:9044:21: error: '::OpenThread' has not been declared
     HANDLE thread = ::OpenThread(SYNCHRONIZE | THREAD_QUERY_INFORMATION,
                     ^

13:31:56 Build Finished (took 3s.12ms)`
```

I tried to build it directly without eclipse. So i used cmake with mingw makefile configuration. But results stay the same when executing mingw32-make
Am i missing something?
Do i need special packages from the mingw installation?

Thanks in advance for your help.

### PR DESCRIPTION
**Pull request by ilmagico**
Fixes #708.

Allows to compile googletest with MinGW when pthreads support is disabled.
Also, the cmake build automatically disables pthreads supportwhen MinGW is used.

Tested on Win7, with MinGW 4.8.1, cmake 3.5.0. All tests pass, except for gmock-matchers_test that fails because of a limitation of MinGW not being able to handle "too many sections", most likely unrelated to the issue being addressed here (see below).

Unfortunately, I am not able to (legally) test with MSVC compiler, anybody please help test.

Also tested on Linux, although I expect no differences.

cmake command line used for testing:
`cmake -G "MinGW Makefiles" -Dgtest_build_samples=ON -Dgmock_build_samples=ON -Dgtest_build_tests=ON -Dgmock_build_tests=ON ..`

MinGW "too many section" issue:
```
c:/mingw-2/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/as.exe: CMakeFiles\gmock-matchers_test.dir\test\gmock-matchers_test.cc.obj: too many sections (43319)
C:\Users\ilmagico\AppData\Local\Temp\cc4PXqrl.s: Assembler messages:
C:\Users\ilmagico\AppData\Local\Temp\cc4PXqrl.s: Fatal error: can't write CMakeFiles\gmock-matchers_test.dir\test\gmock-matchers_test.cc.obj: File too big
c:/mingw-2/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/as.exe: CMakeFiles\gmock-matchers_test.dir\test\gmock-matchers_test.cc.obj: too many sections (43319)
C:\Users\ilmagico\AppData\Local\Temp\cc4PXqrl.s: Fatal error: can't close CMakeFiles\gmock-matchers_test.dir\test\gmock-matchers_test.cc.obj: File too big
```
and (after using `make --keep-going`)
```
98% tests passed, 1 tests failed out of 59

Total Test time (real) =  26.45 sec

The following tests FAILED:
          9 - gmock-matchers_test (Not Run)
```
Apparently this limitation is lifted in recent versions of MinGW64 (when compiling in 64-bit mode), if I get a chance I'll try that too.

### CODE REVIEW

File: googletest/include/gtest/internal/gtest-port.h [hunk 1]
```diff
@@ -396,10 +396,16 @@
 #  include <io.h>
 # endif
 // In order to avoid having to include <windows.h>, use forward declaration
-// assuming CRITICAL_SECTION is a typedef of _RTL_CRITICAL_SECTION.
+#if GTEST_OS_WINDOWS_MINGW
+// MinGW defined _CRITICAL_SECTION and _RTL_CRITICAL_SECTION as two
+// separate (equivalent) structs, instead of using typedef
+typedef struct _CRITICAL_SECTION GTEST_CRITICAL_SECTION;
```
Comment (orgads) [inline googletest/include/gtest/internal/gtest-port.h]: This breaks compilation with MinGW 5.2.0.

**Comment by orgads** [comment]
Tested with MSVC. All compiles. With recent MinGW it is broken though.

**Comment by andoks** [comment]
Seems to work with MSVC 2010, fails when trying to build with MinGW (g++ -v: gcc version 4.9.2 (i686-posix-dwarf-rev1, Built by MinGW-W64 project) )


`cmake -G "MSYS Makefiles" -H. -B_builds -DCMAKE_INSTALL_PREFIX=$(pwd)/_install `
`cmake --build _builds/ --target install`

First error is: 
> googletest-fix-mingw-threads/googletest/src/gtest-port.cc:242:45: error: cannot convert 'CRITICAL_SECTION* {aka _RTL_CRITICAL_SECTION*}' to 'GTEST_CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' in initialization
       critical_section_(new CRITICAL_SECTION) {

**Comment by andoks** [comment]
I believe I was experiencing the same issue late last year (see issue #606 and PR #608). 

As far as I can understand the original issue is that commit a6340420 introduced internal testing of GTests use of threads, and tried to disable pthreads on MinGW but failed.

I tried building GTest master with [somethings similar](https://github.com/google/googletest/files/397544/0001-fix-properly-disable-pthreads-when-using-MinGW.patch.txt) to PR #608 above, and properly disabling pthreads makes the build work on MinGW.

Maybe the best way to go about it would be to first properly disable pthreads, then implement the threading testing on windows?

**Comment by BillyDonahue** [comment]
This looks good. Thanks.

File: googletest/include/gtest/internal/gtest-port.h (hunk 1 above)
Comment (dneto0) [inline googletest/include/gtest/internal/gtest-port.h]: Same for me.  This breaks compilation on Linux with MinGW 4.8.2

```
gtest-port.cc:242:45: error: cannot convert ‘CRITICAL_SECTION* {aka _RTL_CRITICAL_SECTION*}’ to ‘GTEST_CRITICAL_SECTION* {aka _CRITICAL_SECTION*}’ in initialization
       critical_section_(new CRITICAL_SECTION) {
```

Comment (KindDragon) [inline googletest/include/gtest/internal/gtest-port.h]: Fix this in PR #856, but a lot of test still failing with MinGW

**Comment by Fazer2** [comment]
This merge broke compilation on Windows with MinGW 5.3 x32. It comes bundled with Qt 5.7 SDK. Now I get errors like this:

> In file included from ..\..\..\lib\googletest\googletest\src\gtest-all.cc:45:0:
> D:/dev/lib/googletest/googletest/src/gtest-port.cc: In constructor 'testing::internal::Mutex::Mutex()':
> D:/dev/lib/googletest/googletest/src/gtest-port.cc:242:45: error: cannot convert 'CRITICAL_SECTION* {aka _RTL_CRITICAL_SECTION*}' to 'GTEST_CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' in initialization
>        critical_section_(new CRITICAL_SECTION) {
>                                              ^
> D:/dev/lib/googletest/googletest/src/gtest-port.cc:243:48: error: cannot convert 'GTEST_CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to 'LPCRITICAL_SECTION {aka _RTL_CRITICAL_SECTION*}' for argument '1' to 'void InitializeCriticalSection(LPCRITICAL_SECTION)'
>    ::InitializeCriticalSection(critical_section_);
>                                                 ^
> In file included from D:/dev/lib/googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
>                  from D:/dev/lib/googletest/googletest/include/gtest/gtest.h:58,
>                  from ..\..\..\lib\googletest\googletest\src\gtest-all.cc:39:
> D:/dev/lib/googletest/googletest/include/gtest/internal/gtest-port.h:402:16: note: class type 'GTEST_CRITICAL_SECTION {aka _CRITICAL_SECTION}' is incomplete
>  typedef struct _CRITICAL_SECTION GTEST_CRITICAL_SECTION;
>                 ^
> In file included from ..\..\..\lib\googletest\googletest\src\gtest-all.cc:45:0:
> D:/dev/lib/googletest/googletest/src/gtest-port.cc: In destructor 'testing::internal::Mutex::~Mutex()':
> D:/dev/lib/googletest/googletest/src/gtest-port.cc:253:46: error: cannot convert 'GTEST_CRITICAL_SECTION* {aka _CRITICAL_SECTION*}' to 'LPCRITICAL_SECTION {aka _RTL_CRITICAL_SECTION*}' for argument '1' to 'void DeleteCriticalSection(LPCRITICAL_SECTION)'
>      ::DeleteCriticalSection(critical_section_);
>                                               ^
