### ISSUE TITLE
Build broken on Ubuntu 16.04/GCC 5.4.0

### ISSUE THREAD

**Issue by gpenghe** [google/googletest#1887]
Hello, the recent commit 4bb49ed640e34e23187ad7ea689693ef9927033f breaks the build on Ubuntu 16.04/GCC 5.4.0 with many errors like this:

    /foo/googletest/googletest/include/gtest/internal/gtest-port.h:1200:3: error: identifier 'nullptr' is a keyword in C++11 [-Werror=c++0x-compat]

GCC 5.4.0 might be old, but it's the default for Ubuntu 16.04, which is used by our standard docker and I presume is used by many other deployments as well.

**Comment by gpenghe** [comment]
Haha, just noticed the commit comments and release notes that pre-C++ 11 is no longer supported. OK then.
