### ISSUE TITLE
Compilation error for unused variable on gtest_unittest.cc for record_property_env

### ISSUE THREAD

**Issue by gdsotirov** [google/googletest#1825]
I'm getting the following error when trying to compile GoogleTest 1.8.1 with GCC 5.5.0 on Slackware Linux 14.2:

```
/usr/src/tmp/googletest-release-1.8.1/googletest/test/gtest_unittest.cc:2120:21: error: '{anonymous}::record_property_env' defined but not used [-Werror=unused-variable]
 static Environment* record_property_env =
                     ^
cc1plus: all warnings being treated as errors
```

The problem seems to be introduced with commit 3299a23 from 2018-02-23. Just adding back the macro GTEST_ATTRIBUTE_UNUSED_ fixes the issue.

**Comment by gennadiycivil** [comment]
@gdsotirov  Thank you for this find. 
Please submit a PR and we can evaluate
Thanks

**Comment by gdsotirov** [comment]
Created pull request #1828 as requested.
