### ISSUE TITLE
#1710 breaks builds on GCC8

### ISSUE THREAD

**Issue by iamthebot** [google/googletest#1711]
Our builds just started breaking due to #1710 from a misleading indentation error:

```
/mnt/<...>/googletest-src/googletest/src/gtest-death-test.cc:238:3: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
   else
   ^~~~
/mnt/<...>/googletest-src/googletest/src/gtest-death-test.cc:240:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'else'
     msg << " See https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#death-tests-and-threads"
     ^~~
cc1plus: all warnings being treated as errors
```

@gennadiycivil

**Comment by iamthebot** [comment]
Looks like aligning the indentation (using an autoformatter) gets rid of the error.

**Comment by suisuiwudi** [comment]
Same issue on GCC7.
```
The C compiler identification is GNU 7.3.0
The CXX compiler identification is GNU 7.3.0
```

**Comment by elmodaddyb** [comment]
Hello All, 

Recently faced a similar issue building from master using bdf5fd3a98942f57385c8977dab965874d3c5d53:

```
Setting environment variables
$ export CXX=g++-6
$ export CC=gcc-6
```

`g++5.0`, `g++4.9`, `clang++-4.0`... work without incident

**Comment by gennadiycivil** [comment]
Thank you for reporting this. Would you be able to provide a travis configuration with GCC 8? So such things should be automatically caught 
Thanks

**Comment by gennadiycivil** [comment]
it should be good now
