### ISSUE TITLE
Link Errors after Upgrading to v1.11.0 from v1.10.0

### ISSUE THREAD

**Issue by DeveloperPaul123** [google/googletest#3578]
**Describe the bug**

We recently upgraded to `v1.11.0` from `v1.10.0` of `googletest` and are now experiencing linker errors. In some of our smaller test suites, I was able to deduce that `googletest` is expecting a stream operator for classes that are compared using `EXPECT_EQ`. After adding the stream operator, or switching to using `EXPECT_TRUE(class1 == class2)`, the link errors went away. 

However, we are seeing similar issues in some of our larger test suites and it's unclear what the cause is/could be. Is there something we are missing with this upgrade? 

Build error output:

```
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl testing::internal2::PrintBytesInObjectTo(unsigned char const *,unsigned __int64,class std::basic_ostream<char,struct std::char_traits<char> > *)" (__imp_?PrintBytesInObjectTo@internal2@testing@@YAXPEBE_KPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl testing::internal::MatcherBase<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>::DescribeTo(class std::basic_ostream<char,struct std::char_traits<char> > *)const " (__imp_?DescribeTo@?$MatcherBase@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@internal@testing@@QEBAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z)
      Error LNK1120: 2 unresolved externals
```

**Does the bug persist in the most recent commit?**

We are using the latest release, `v1.11.0`, not the latest commit. 

**What operating system and version are you using?**

Windows 10 Pro.

**What compiler and version are you using?**

 C/C++ Optimizing Compiler Version 19.29.30133

**What build system are you using?**

CMake `3.21.0`

**Additional context**

We build `googletest` along with our project and set `GTEST_LINKED_AS_SHARED_LIBRARY` for each unit test sweet. We build `googletest` as a shared library with `gtest_force_shared_crt` set to `ON`.

**Comment by derekmauro** [comment]
> We recently upgraded to v1.11.0 from v1.10.0 of googletest and are now experiencing linker errors. In some of our smaller test suites, I was able to deduce that googletest is expecting a stream operator for classes that are compared using EXPECT_EQ. After adding the stream operator, or switching to using EXPECT_TRUE(class1 == class2), the link errors went away.

This is expected.

> However, we are seeing similar issues in some of our larger test suites and it's unclear what the cause is/could be. Is there something we are missing with this upgrade?

We need reproduction instructions to look into the issue. Please re-open this issue with instructions.

**Comment by DeveloperPaul123** [comment]
> This is expected.

Does this mean we now need stream operators for all classes we want to test?

**Comment by vchigrin** [comment]
To whom it may be helpful:
I experienced same issues. Then discovered mistake in my build scripts. Compiler used headers from one gtest version, but linking were performed with libraries from different gtest version.
