### ISSUE TITLE
gmock ReturnArg and SetArgReferee regression in googletest 1.11.0

### ISSUE THREAD

**Issue by f00ale** [google/googletest#3733]
**Describe the bug**

I'm in the process of updating a codebase from gtest/gmock 1.8.1 to 1.11.0 but have run into problems with the gmock actions `ReturnArg` and `SetArgReferee`. Code that compiled with 1.8.1 doesn't compile with 1.11.0. It seems like the regression was introduced somewhere between 1.10 and 1.11.

**Steps to reproduce the bug**

Create a mocked function taking a reference as the single argument, returning a reference of the same type.
Adding an `EXPECT_CALL` with `ReturnArg<0>` as action works in gtest 1.8.1 but not with 1.11.0.
The 1.11.0 version complains about the tuple index being out of range.

Example in compiler explorer: https://godbolt.org/z/bjYffY6f5 (works with version 1.10.0 but not with trunk)

Adding const to the return type of the mocked function makes it compile though (But then of course I get the wrong signature on my mocked function)

Adding an `SetArgReferee<0>(...)` action also gives a compilation error where 1.8.1 worked. 
The compilation error says that the compiler cannot convert the SetArgRefereeAction into a const Action 
Here the const workaround doesn't work though.

Example: https://godbolt.org/z/hcr6rTrjf

**Does the bug persist in the most recent commit?**

Yes

**What operating system and version are you using?**

Ubuntu 18.04

**What compiler and version are you using?**

gcc 7.5, gcc 11, clang 9

**What build system are you using?**

cmake 3.18

**Additional context**

--

**Comment by sbenzaquen** [comment]
It seems the change to ReturnArg broke non-const ref arguments.
In:

```
template <size_t k>
struct ReturnArgAction {
  template <typename... Args>
  auto operator()(const Args&... args) const ->
      typename std::tuple_element<k, std::tuple<Args...>>::type {
    return std::get<k>(std::tie(args...));
  }
};
```

It is not allowing non-const arguments to be returned, so it can't be used as a `T&(T&)` action.

**Comment by dinord** [comment]
In the given example on GoogleTest v1.10, `SetArgReferee` only happens to work on GCC, but on Clang it fails with SIGILL (132): https://godbolt.org/z/d1MG4Tx9o

The implementation of `SetArgReferee` never had a return statement. In v1.10, it had a template return type. In the example, this type was inferred from the mocked method to be `std::vector<char>&`.
However, in v1.11, `SetArgReferee` was correctly rewritten with a concrete return type, `void`.

Unless the mocked method returns `void`, `SetArgReferee` needs to be combined action whose return type matches that of the mocked method. For example, using `DoAll` and `ReturnArg` like so: https://godbolt.org/z/4ffazfvba

**Comment by dinord** [comment]
The regression in `ReturnArgAction` should be fixed at 0b7798b2fba340969a0cf83698e5c0a2e25b7dbc.
Unfortunately, godbolt seems to be stuck on an older commit of GoogleTest.

Please reopen if the bug persists
