### ISSUE TITLE
Return doesn't work with boost::function in version >= 1.10

### ISSUE THREAD

**Issue by antasp** [google/googletest#3535]
Compiling with gcc >= 6.1 fails with the following error:

```
> `opt/compiler-explorer/libs/boost_1_77_0/boost/function/function_template.hpp:1086:16: error: use of deleted function 'constexpr std::tuple< <template-parameter-1-1> >::tuple(const std::tuple< <template-parameter-1-1> >&) [with _Elements = {boost::function<void()>&&}]'
>      base_type(f)`

```

Sample code:

```
#include <boost/function.hpp>
#include <gtest/gtest.h>
#include <gmock/gmock.h>


class M{
public:

    MOCK_METHOD1(f, bool(boost::function<void()>));

};

TEST(A,B){
    M m;

    EXPECT_CALL(m, f(testing::_)).WillRepeatedly(testing::Return(true));
}

int main(){
    return 0;
}
```

**Comment by antasp** [comment]
Not an issue anymore in trunk
