### ISSUE TITLE
XCode 8.1 build failure on gmock-actions.h due to missing user constructor for ExcessiveArg type

### ISSUE THREAD

**Issue by dneto0** [google/googletest#3128]
A colleague using XCode 8.1 reports a build failure 

```
In file included from /Users/dkoch/khronos/github/glslang/External/googletest/googlemock/src/gmock-all.cc:39:
In file included from /Users/dkoch/khronos/github/glslang/External/googletest/googlemock/include/gmock/gmock.h:59:
/Users/dkoch/khronos/github/glslang/External/googletest/googlemock/include/gmock/gmock-actions.h:1523:31: error: 
      default initialization of an object of const type 'const testing::internal::ExcessiveArg' without a
      user-provided default constructor
    static const ExcessiveArg kExcessArg;
                              ^
                                        {}
1 error generated.
```

This appears to be caused by https://github.com/google/googletest/commit/fbef0711cfce7b8f149aac773d30ae48ce3e166c

**Comment by dneto0** [comment]
cc: @dgkoch

**Comment by greg-lunarg** [comment]
This is also a problem with glslang Travis CI build. See https://github.com/KhronosGroup/glslang/pull/2472

**Comment by goodlegs** [comment]
I'm new to github so sorry for the obvious question; after cloning the repo, I get the above compilation error. Do I need to download an experimental branch containing the fix instead?

**Comment by juan-lunarg** [comment]
@asoffer feel free to close this issue. Or any other google test maintainer. The original reason it was opened doesn't exist anymore.
