### ISSUE TITLE
WithArgs fails to compile if trying to use with class having a templated constructor

### ISSUE THREAD

**Issue by Kova93** [google/googletest#3178]
I'm trying to forward an arg from a call to a mocked method that accepts an object with a templated constructor, but I get a weird compile error. It seems like at some point instead of copying/moving the tuple (that packs the args) itself, it tries to construct the wrapped type with the tuple (and of course it fails to do so).

Here's a minimal reproducible example, and the resulting compile error:

```
#include <gtest/gtest.h>
#include <gmock/gmock.h>

class Foo {
public:
        template<typename T>
        Foo(T x) : _x(x) {}

private:
        int _x;
};

class FooWrapper {
public:
        virtual void doFoo(Foo foo) = 0;
};

void myFooFun(Foo foo) {
}

class MockFooWrapper : public FooWrapper {
public:
        MockFooWrapper() {
                ON_CALL(*this, doFoo).WillByDefault(::testing::WithArg<0>(myFooFun));
        }

        MOCK_METHOD(void, doFoo, (Foo foo), (override));
};
```

```
withargs_min.cc:7:13: error: no viable conversion from 'std::__1::tuple<Foo &&>' to 'int'
        Foo(T x) : _x(x) {}
                   ^  ~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/tuple:232:15: note: in instantiation of function template specialization 'Foo::Foo<std::__1::tuple<Foo &&> >' requested here
            : __value_(_VSTD::forward<_Tp>(__t))
              ^
withargs_min.cc:24:39: note: in instantiation of function template specialization 'testing::internal::WithArgsAction<void (*)(Foo), 0>::operator Action<void, Foo>' requested here
                ON_CALL(*this, doFoo).WillByDefault(::testing::WithArgs<0>(myFooFun));
```

The compiler used was Apple clang v12.0.0

**Comment by hyukmyeong** [comment]
It looks like your code stuck below line if I compile it with g++
which uses std::forward_as_tuple to create tuple objects

https://github.com/google/googletest/blob/master/googlemock/include/gmock/gmock-actions.h#L1028

**Comment by hyukmyeong** [comment]
Hello,  
  
If I compile your code with g++, the log shows below error  
```bash
/usr/include/c++/9/tuple:133:42:   required from ‘constexpr std::_Head_base<_Idx, _Head, false>::_Head_base(_UHead&&) [with _UHead = std::tuple<Foo&&>; long unsigned int _Idx = 0; _Head = Foo]’
/usr/include/c++/9/tuple:349:38:   required from ‘constexpr std::_Tuple_impl<_Idx, _Head>::_Tuple_impl(_UHead&&) [with _UHead = std::tuple<Foo&&>; long unsigned int _Idx = 0; _Head = Foo]’
/usr/include/c++/9/tuple:627:61:   required from ‘constexpr std::tuple<_Elements>::tuple(_UElements&& ...) [with _UElements = {std::tuple<Foo&&>}; typename std::enable_if<((std::tuple<_Elements>::_TMC<_UElements ...>::_MoveConstructibleTuple<_UElements ...>() && std::tuple<_Elements>::_TMC<_UElements ...>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (sizeof... (_Elements) >= 1)), bool>::type <anonymous> = true; _Elements = {Foo}]’
../../../googletest/googlemock/include/gmock/gmock-actions.h:905:76:   required from ‘testing::internal::WithArgsAction<InnerAction, I>::operator std::function<R(Args ...)>() const [with R = void; Args = {Foo}; InnerAction = void (*)(Foo); long unsigned int ...I = {0}]’
./test/gtest_main.cpp:46:64:   required from here
./test/gtest_main.cpp:27:21: error: cannot convert ‘std::tuple<Foo&&>’ to ‘int’ in initialization
   27 |       Foo(T x) : _x(x) {}
      |                     ^
      |                     |
      |                     std::tuple<Foo&&>
```

gmock-actions.h 905 in my code is same to https://github.com/google/googletest/blob/master/googlemock/include/gmock/gmock-actions.h#L1028 in main branch
It leads to https://github.com/google/googletest/blob/master/googlemock/include/gmock/gmock-actions.h#L498
I'm not sure but there is a function call which needs instantiation in the end

**Comment by stefanhaller** [comment]
It seems this is not related to `WithArg`, but to `WillByDefault`; the same error happens when you replace your `ON_CALL` statement with
```
ON_CALL(*this, doFoo).WillByDefault(::testing::Return());
```

The failure was introduced with 9494c45e75a5554; I couldn't immediately see a straightforward way to fix it, but I also didn't try very hard.

One workaround is to pass your `Foo` type by const reference, so if you can change your `FooWrapper` to
```
  virtual void doFoo(const Foo& foo) = 0;
```
(and the `MOCK_METHOD` accordingly, of course), this will fix it.

**Comment by sbenzaquen** [comment]
These kind of unconstrained implicit conversion constructors templates are very brittle. I strongly suggest using a different design in the class.
They get in the way of generic programming, lie to type traits, can prevent SFINAE-based detection, and give very surprising behavior when overloaded operators are in the mix. Simply including a header somewhere in your transitive dependency can cause the program to break.
They will not play nicely with some standard types that try to inspect the inputs through type_traits, like `std::tuple`, `std::optional`, `std::any`, etc.

**Comment by Omar-py** [comment]
Do you know who am i ?

**Comment by Kova93** [comment]
> 
> 
> These kind of unconstrained implicit conversion constructors templates are very brittle. I strongly suggest using a different design in the class.
> They get in the way of generic programming, lie to type traits, can prevent SFINAE-based detection, and give very surprising behavior when overloaded operators are in the mix. Simply including a header somewhere in your transitive dependency can cause the program to break.
> They will not play nicely with some standard types that try to inspect the inputs through type_traits, like `std::tuple`, `std::optional`, `std::any`, etc.

Using type traits in the constructor solved the issue, thanks

```
        template<typename T, std::enable_if_t<std::is_convertible_v<T, int>, int> = 0>
        Foo(T x) : _x(x) {}
```
